---
driver:
  name: ec2
  security_group_ids: [ sg-977bdef2 ]
  aws_ssh_key_id: us-east1-jdunn

transport:
  ssh_key: ~/.ssh/us-east1-jdunn.pem

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.12.15 # a chef release without yum built in

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[yum::default]
      - recipe[yum_test::test_repo]
  - name: global_conflig
    run_list:
      - recipe[yum::default]
      - recipe[yum_test::test_globalconfig_two]
